# Generated by Django 4.1.5 on 2023-01-26 02:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("recipes", "0009_remove_mealplan_owner_pantry_food_pantry_foodqty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                ("title", models.CharField(max_length=128)),
                ("currentDate", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="MealUser",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("meal", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("date", models.DateField(default=datetime.date(2023, 1, 25))),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
        ),
    ]
