# Generated by Django 4.1.5 on 2023-01-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealplan",
            name="currentDate",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
