# Generated by Django 4.1.5 on 2023-01-24 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0002_alter_mealplan_currentdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="MealUser",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
