# Generated by Django 4.1.5 on 2023-01-24 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_mealplan_currentdate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MealPlan",
        ),
    ]
