# Generated by Django 4.1.5 on 2023-01-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
