# Generated by Django 4.1.5 on 2023-01-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ratings",
            field=models.IntegerField(null=True),
        ),
    ]
