# Generated by Django 4.1.5 on 2023-01-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_remove_recipe_ratings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(default=None, upload_to="images/"),
        ),
    ]
