# Generated by Django 4.1.5 on 2023-01-26 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0008_pantry_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealplan",
            name="owner",
        ),
        migrations.AddField(
            model_name="pantry",
            name="food",
            field=models.CharField(default="none", max_length=255),
        ),
        migrations.AddField(
            model_name="pantry",
            name="foodQty",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pantry",
            name="herb",
            field=models.CharField(default="none", max_length=255),
        ),
        migrations.AddField(
            model_name="pantry",
            name="herbQty",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pantry",
            name="spice",
            field=models.CharField(default="none", max_length=255),
        ),
        migrations.AddField(
            model_name="pantry",
            name="spiceQty",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pantry",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="MealPlan",
        ),
    ]
